server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5433/pontal
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.pontal.dto
mybatis.configuration.map-underscore-to-camel-case=true
