server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5433/pontal
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.pontal.dto
mybatis.configuration.map-underscore-to-camel-case=true

#.envファイル(環境変数)で注入
cognito.region=${COGNITO_REGION:ap-northeast-1}
cognito.user-pool-id=${COGNITO_USER_POOL_ID:}

#PosgreSQL(外部DB)の自動実行を有効化
spring.sql.init.mode=always

#フォルダの中を見るように指定
spring.sql.init.schema-locations=classpath:schema/*.sql

# AWS S3の設定
aws.s3.bucket=${AWS_S3_BUCKET:}
aws.s3.region=${AWS_S3_REGION:ap-southeast-2}
